import type { Metadata } from "next";
import { Recursive, Jaini } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/components/AuthProvider";

const recursive = Recursive({
  variable: "--font-recursive",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const jaini = Jaini({
  variable: "--font-work-sans",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Carta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${recursive.variable} antialiased`}>
        <div className="z-0 relative w-screen min-h-screen h-full bg-background">
          <AuthProvider>{children}</AuthProvider>
        </div>
      </body>
    </html>
  );
}
